apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: banking

spec:

  selector:
    app: banking-backend

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

  type: ClusterIP
